### ISSUE TITLE
mnist-cnn

### ISSUE THREAD

**Issue by Amri95** [ZhaoqxCN/PYNQ-CNN-ATTEMPT#1]
![image](https://user-images.githubusercontent.com/37174642/91129589-389e0200-e6e5-11ea-997c-e8b9a0ee2935.png)

**Comment by ZhaoqxCN** [comment]
The 'main.cpp' is the test file for 'cnn.cpp', it should not be set as source file, and the 'cnn' function should be set as the main function.

**Comment by Amri95** [comment]
Could you please provide the HLS files for the MLP used for MNIST ?

Best regards

**Comment by ZhaoqxCN** [comment]
You can get the full HLS project files in this [link](https://pan.baidu.com/s/1qayhkKiDjvm9j1Xb-vuNGA) in 7 days. Code: q5h9.

**Comment by Amri95** [comment]
Thankyou, In addition I would also like to know the source code to obtain
the .h5 model for MLP and CNN.

Best regards

**Comment by ZhaoqxCN** [comment]
You can easily get the code examples in Keras [docs](https://keras.io/examples/vision/mnist_convnet/).

**Comment by Amri95** [comment]
Hello,
I cannot access the link you sent me. Could you please sent me in here
(Gmail).
I will appreciate it.
Thank you

**Comment by ZhaoqxCN** [comment]
You can try this site: keras.io, there are many examples, including MINST convnet.

**Comment by Amri95** [comment]
I want the HLS source, please. If you can share it here. Thank you.

**Comment by Amri95** [comment]
> You can get the full HLS project files in this [link](https://pan.baidu.com/s/1qayhkKiDjvm9j1Xb-vuNGA) in 7 days. Code: q5h9.

Could you please send me the full HLS source for MLP and CNN?  amritaranamagar60@gmail.com

**Comment by ghost** [comment]
HI, @ZhaoqxCN How did you calculate the CNN parameters in each layer in main.cpp file?


               _AXI_VAL status = 1;
		AXI_VAL batch_size = 0;
		AXI_VAL Ker_DIM = 3;
		AXI_VAL In_CH = 1;
		AXI_VAL In_DIM = 28;
		AXI_VAL Out_CH = 16;
		AXI_VAL Out_DIM = 26;_
